name: RNW CI $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

variables:
  - template: variables/msbuild.yml
  - group: RNW Secrets
  - group: platform-override-zero-permission-token

stages:
  - stage: Setup
    jobs:
      - job: Setup
        variables:
          - template: variables/vs2019.yml
        steps:
          - template: templates/configure-git.yml

          - template: templates/yarn-install.yml

          - script: yarn build
            displayName: yarn build

          - script: npx --no-install beachball publish --branch origin/$(Build.SourceBranchName) -n $(npmAuthToken) -yes -m "applying package updates ***NO_CI***" --bump-deps  --access public --no-git-tags --no-push --no-publish 
            displayName: Beachball Determine versions

          - template: templates/set-version-vars.yml

          - template: templates/publish-version-vars.yml

  - template: stages.yml
    parameters:
      buildEnvironment: Continuous