name: $(Date:yyyyMMdd).$(Rev:r)

trigger: none # will disable CI builds entirely

pr:
  - master
  - "*-stable"

variables:
  - template: variables/msbuild.yml
  - group: platform-override-zero-permission-token

stages:
  - stage: Setup
    jobs:
      - job: Setup
        variables:
          - template: variables/vs2019.yml
        steps:
          - task: powershell@2
            name: checkPayload
            displayName: "Check if build is required for this PR"
            inputs:
              targetType: filePath
              filePath: .ado/scripts/shouldSkipPRBuild.ps1
          
          - template: templates/set-version-vars.yml
          - template: templates/publish-version-vars.yml
          
  - template: stages.yml
    parameters:
      buildEnvironment: PullRequest